Repository Nathanvititoe/cashflow-life, pull requests merged in 2025-02, with the labels that each got.

#12 fixed ts error and updated packages
  app/components/TransactionLog/TransactionLog.tsx
  package-lock.json
  package.json
Labels: enhancement

#14 Snacks compatibility fix
  .vscode/settings.json
  Buildings_For_Sale/Automated_Business.ts
  Buildings_For_Sale/Depressed_Market_Home.ts
  Buildings_For_Sale/Desirable_Duplex.ts
  Buildings_For_Sale/Divorced_Home.ts
  Buildings_For_Sale/Family_Car_Wash.ts
  Buildings_For_Sale/Forced_Sale_4_Plex.ts
  Buildings_For_Sale/Foreclosed_Condo.ts
  Buildings_For_Sale/Foreclosed_Home.ts
  Buildings_For_Sale/Highway_Home.ts
  Buildings_For_Sale/Hospital_Bill_Duplex.ts
  Buildings_For_Sale/Manager_Home.ts
  Buildings_For_Sale/Moving_Seller_Home.ts
  Buildings_For_Sale/Moving_State_4_Plex.ts
  Buildings_For_Sale/Parents_Condo.ts
  Buildings_For_Sale/Professional_Partnership_8_Plex.ts
  Buildings_For_Sale/Reinvesting_Owner_8_Plex.ts
  Buildings_For_Sale/Repossessed_Home.ts
  Buildings_For_Sale/Unit_Apartment_Home.ts
  Buildings_For_Sale/Young_Couple_Condo.ts
  app/components/Header/Header.tsx
  app/components/Menus/TabMenu.tsx
  app/components/Menus/UserMenu.tsx
  app/components/Properties/Properties.tsx
  app/components/QrCodeScanner/ScannerButton.tsx
  app/components/QrCodeScanner/ScannerModal.tsx
  app/components/TransactionLog/LatestTransaction.tsx
  app/components/TransactionLog/TransactionLog.tsx
  app/components/UserFinances/FinancialOverview.tsx
  app/components/UserFinances/FinancialStatement.tsx
  app/components/features/ConfirmationModal.tsx
  app/index.tsx
  data/market_cards.ts
  data/small_cards.ts
  eslintrc.ts
  interfaces/profession.ts
  package-lock.json
  package.json
  prettier.config.js
  testData/blankUser.ts
  testData/tempTestData.ts
  testData/testProperties.ts
  testData/testTransactions.ts
  tsconfig.json
Labels: Developer Improvement

#15 fixing dependencies for expo
  package-lock.json
  package.json
Labels: Developer Improvement

#16 resolving snack conflicts
  app/components/features/ConfirmationModal.tsx
  package-lock.json
  package.json
  tsconfig.json
Labels: Developer Improvement

#20 added polyfixes
  metro.config.ts
  package-lock.json
  package.json
Labels: Developer Improvement

#23 change
  app.config.ts
  package-lock.json
  package.json
Labels: Developer Improvement

#24 Added theme colors
  app/components/Header/Header.tsx
  app/components/Menus/TabMenu.tsx
  app/components/Menus/UserMenu.tsx
  app/components/Properties/Properties.tsx
  app/components/QrCodeScanner/ScannerButton.tsx
  app/components/QrCodeScanner/ScannerModal.tsx
  app/components/TransactionLog/LatestTransaction.tsx
  app/components/TransactionLog/TransactionLog.tsx
  app/components/UserFinances/FinancialOverview.tsx
  app/components/UserFinances/FinancialStatement.tsx
  app/components/features/ConfirmationModal.tsx
  app/index.tsx
  interfaces/theme.ts
  package-lock.json
  package.json
Labels: enhancement, Developer Improvement

#26 Cleaned up package lock
  package-lock.json
  package.json
Labels: Developer Improvement

#28 Changed the navigation theme, to stand out more.
  .gitignore
Labels: Developer Improvement
